name: Build OSX wheels

env:
  CIBW_ARCHS_MACOS: "x86_64"

on: [push]

jobs:
  build_osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '>=3.7 <3.13'
    - name: Download and build MeCab
      shell: bash
      run: |
        .github/macos-build.sh

    - name: Upload Wheels
      uses: actions/upload-artifact@v1
      with: 
        name: osx-wheels
        path: dist
    - name: Publish to PyPI if tagged
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/fugashi*

